version: "3"

services:

  dddmr_hardware:
    image: dddmr_gtsam:x64
    command: bash -c "source /opt/ros/humble/setup.bash && cd /root/dddmr && colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release && source install/setup.bash && ros2 launch cmd_controller dddmr_ros2_hardware.launch"
    network_mode: host
    privileged: true
    environment:
      #FASTRTPS_DEFAULT_PROFILES_FILE: /root/DDDMR_ros2/docker/docker_file/rtps_udp_profile.xml
      #RMW_FASTRTPS_USE_QOS_FROM_XML: 1
      ROS_DOMAIN_ID: 3
      DISPLAY:
      QT_X11_NO_MITSHM: 1
    container_name: dddmr_hardware
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
      - "/dev:/dev"
      - "${HOME}/dddmr:/root/dddmr"
      #- "${HOME}/ros2_bags:/root/ros2_bags"
      
 
