version: "3"

services:

  dddmr_bagrecord:
    image: dddmr_gtsam:amd64
    command: bash -c "source /root/dddmr/install/setup.bash && cd /root/dddmr && ros2 bag record /lslidar_point_cloud /odom "
    network_mode: host
    privileged: true
    environment:
      #FASTRTPS_DEFAULT_PROFILES_FILE: /root/DDDMR_ros2/docker/docker_file/rtps_udp_profile.xml
      #RMW_FASTRTPS_USE_QOS_FROM_XML: 1
      ROS_DOMAIN_ID: 3
      DISPLAY:
      QT_X11_NO_MITSHM: 1
    container_name: dddmr_bagrecord
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
      - "/dev:/dev"
      - "${HOME}/dddmr:/root/dddmr"
      #- "${HOME}/ros2_bags:/root/ros2_bags"
      #- "${HOME}/ros2_bags_record:/root/ros2_bags_record"
      
  dddmr_camerarecord:
    image: dddmr_gtsam:amd64
    command: bash -c "cd /root/dddmr && gst-launch-1.0 v4l2src device=/dev/video4 ! queue ! videoscale ! video/x-raw, width=1920, height=1080, framerate=15/1 ! videoconvert ! x264enc ! flvmux ! filesink location=dddmr.mp4"
    network_mode: host
    privileged: true
    environment:
      ROS_DOMAIN_ID: 3
      DISPLAY:
      QT_X11_NO_MITSHM: 1
    container_name: dddmr_camerarecord
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
      - "/dev:/dev"
      - "${HOME}/dddmr:/root/dddmr"
      #- "${HOME}/ros2_bags:/root/ros2_bags"
      #- "${HOME}/ros2_bags_record:/root/ros2_bags_record"
 
