version: "3"

services:

  dddmr_dev:
    image: dddmr_gtsam:x64
    command: bash -c "source /opt/ros/humble/setup.bash && sleep infinity"
    network_mode: host
    privileged: true
    environment:
      #FASTRTPS_DEFAULT_PROFILES_FILE: /root/DDDMR_ros2/docker/docker_file/rtps_udp_profile.xml
      #RMW_FASTRTPS_USE_QOS_FROM_XML: 1
      ROS_DOMAIN_ID: 3
      DISPLAY:
      QT_X11_NO_MITSHM: 1
    container_name: dddmr_dev
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
      - "/dev:/dev"
      - "${HOME}/dddmr:/root/dddmr"
      - "${HOME}/dddmr_bags:/root/dddmr_bags"
      #- "${HOME}/ros2_bags:/root/ros2_bags"
      #- "${HOME}/ros2_bags_record:/root/ros2_bags_record"
      #- "${HOME}/ros2_pcd_data:/root/ros2_pcd_data"
      #- "${HOME}/ws_other:/root/ws_other"
      
 
