FROM dddmr_gtsam:x64

#install cuda 12.6
#see: https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&Distribution=Ubuntu&target_version=22.04&target_type=deb_local
RUN wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-ubuntu2204.pin
RUN mv cuda-ubuntu2204.pin /etc/apt/preferences.d/cuda-repository-pin-600
RUN /bin/bash -c "cd /tmp && wget https://developer.download.nvidia.com/compute/cuda/12.6.3/local_installers/cuda-repo-ubuntu2204-12-6-local_12.6.3-560.35.05-1_amd64.deb"
RUN /bin/bash -c "cd /tmp && dpkg -i cuda-repo-ubuntu2204-12-6-local_12.6.3-560.35.05-1_amd64.deb"
RUN /bin/bash -c "cd /tmp && cp /var/cuda-repo-ubuntu2204-12-6-local/cuda-*-keyring.gpg /usr/share/keyrings/"
RUN /bin/bash -c "apt-get update"
RUN /bin/bash -c "apt-get -y install cuda-toolkit-12-6"

#install cudnn 9.6
#see: https://developer.nvidia.com/cudnn-downloads?target_os=Linux&target_arch=x86_64&Distribution=Ubuntu&target_version=22.04&target_type=deb_local
RUN /bin/bash -c "cd /tmp && wget https://developer.download.nvidia.com/compute/cudnn/9.6.0/local_installers/cudnn-local-repo-ubuntu2204-9.6.0_1.0-1_amd64.deb"
RUN /bin/bash -c "cd /tmp && dpkg -i cudnn-local-repo-ubuntu2204-9.6.0_1.0-1_amd64.deb"
RUN /bin/bash -c "cd /tmp && cp /var/cudnn-local-repo-ubuntu2204-9.6.0/cudnn-*-keyring.gpg /usr/share/keyrings/"
RUN /bin/bash -c "apt-get update"
RUN /bin/bash -c "apt-get -y install cudnn"

#install pytorch
RUN pip3 install pip-versions
RUN pip-versions list torch
RUN pip3 install torch==2.5.1
RUN pip3 install torchvision==0.20.1
RUN pip3 install torchaudio==2.5.1
RUN /bin/bash -c "export PATH=${PATH}:/usr/local/cuda/bin && export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/local/cuda/lib64 && pip3 install pycuda==2024.1.2"
RUN /bin/bash -c "echo 'export PATH=\${PATH}:/usr/local/cuda/bin' >> ~/.bashrc"
RUN /bin/bash -c "echo 'export LD_LIBRARY_PATH=\${LD_LIBRARY_PATH}:/usr/local/cuda/lib64' >> ~/.bashrc"

#install tensorrt for c++ API
#see: https://docs.nvidia.com/deeplearning/tensorrt/install-guide/index.html
#see for download: https://developer.nvidia.com/tensorrt/download/10x
RUN /bin/bash -c "cd /tmp && wget https://developer.nvidia.com/downloads/compute/machine-learning/tensorrt/10.7.0/local_repo/nv-tensorrt-local-repo-ubuntu2204-10.7.0-cuda-12.6_1.0-1_amd64.deb"
RUN /bin/bash -c "cd /tmp && dpkg -i nv-tensorrt-local-repo-ubuntu2204-10.7.0-cuda-12.6_1.0-1_amd64.deb"
RUN /bin/bash -c "cd /tmp && cp /var/nv-tensorrt-local-repo-ubuntu2204-10.7.0-cuda-12.6/*-keyring.gpg /usr/share/keyrings/ && apt-get update"
RUN apt-get install -y tensorrt
#install tensorrt python
RUN python3 -m pip install --upgrade tensorrt
#install cv2
#TODO install customized opencv 
RUN pip3 install opencv-python matplotlib

CMD ["bash"]
